name: Tharrisio Blog CI/CD

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 20 * * 6' # At 20:20 on Saturdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tharrisio/blog
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: dkr.tharris.io
          cache: ${{ github.event_name != 'schedule' }}
